### ISSUE TITLE
MAP - NRC Reports Since BP 

### ISSUE THREAD

**Issue by ezys** [SkyTruth/alerts#3]
A couple of tasks, ping me when you are done. 
- [x] Count of all incidents in the file Paul gave you, and one of all incidents not touching land (NOT intersecting your US states or counties shapefile)
- [x] GIF of all spills, stacking up month-by-month
- [x] Walk @Ezys through the unit conversion, or paste the formula here. Just want to verify all the conversions were made correctly. 
- [x] Post for future reference the date range of your filter.

**Comment by cjthomas730** [comment]
All incidents: 14287
All incidents not touching land: 9856

**Comment by ezys** [comment]
It just occurred to me that some reports are updates to previously filed reports. Unfortunately, the NRC issues a unique ID number for each. Can you look at one of these reports (For example, report #1067083) and see if there is a way we can exclude these from these tallies?

**Comment by cjthomas730** [comment]
Conversion to cubic meters from gallons in the Field Calculator of QGIS. # of Gallons/ 264.17

The number of gallons was taken from the minimum reported spill volume

**Comment by cjthomas730** [comment]
Filter used:
("incident_d" >= '2010-07-15 11:30:00') AND ("medium_aff" = 'WATER') AND ("calltype" = 'INCIDENT') 

A spatial query was also utilized to remove incidents which touched land.
